name: BottledExp
main: me.sacnoth.bottledexp.BottledExp
version: 1.0.1c
description: Fills the player's XP into a bottle
authors: [sacnoth, CubieX]
database: false
softdepend: [PermissionsEx, zPermissions, bPermissions, PermissionsBukkit, Vault, iConomy]
aliases: flasche

commands:
   bottle:
      description: Fills XP into a bottle.
      aliases: flasche
      usage: /flasche [menge | alles/all] | hilfe/help | version | reload -> Alias=bottle

permissions:
    bottle.use:
        description: Allows filling XP in bottles
        default: op
    bottle.admin:
        description: Allows total control over the plugin
        default: op
        children:
            bottle.use: true
